---
title: "The Art in Machine Learning"
description: "description"
author: "Kevin Ong"
date: "07/11/24"
categories: 
  - ml
---

I would argue most people would compare today's machine learning engineers to the Space Race's rocket scientists. Certainly, your impression of a rocket engine engineer to be of slide rulers galore book nerd, but in actuality, as much as they were scientists and engineers, they were also artists. 

The rockets that brought us to the moon, the [Saturn V](https://en.wikipedia.org/wiki/Saturn_V), each had 5 [Rocketdyne F-1 engines](https://en.wikipedia.org/wiki/Rocketdyne_F-1). Each of these engines had more than three times the thrust of the much more advanced [Space Shuttle main engines](https://en.wikipedia.org/wiki/RS-25). These were the largest rocket engines ever manufactured and still hold that title, and they almost ended the entirety of the moon program. Hundreds of engineers had poured over the design of these engines on paper following theory (to the best they knew it at the time, this was bleeding edge tech), and the day they took to test firing the engines, they exploded. The thrust chamber of the engine was so large that combustion instability led to catastrophic failure of the engine. Without good engines, the Saturn V was doomed to fail without even leaving the launch pad. With little time left to bring man to the moon by the end of the decade, engineers resorted to "doing it live"; they would make design changes, build the engines, and throw them onto the test bench to see what would happen. Much of this process relied less on theory but rather the engineers' intuitions and experiences.

Like back then, the hardest problem today's machine learning engineers face is artisnal: how much data do you need for a "good" model? How do you know if your model is trained properly? ...what can you do about it?

The simple take aways are fail often and fail fast. Make mistakes and learn from them.